#
# Exmample compose configuration
# DO NOT USE FOR PRODUCTION
#

version: "3.7"

services:
  app:
    build:
      context: .
      target: development
    command: dockerize -wait tcp://postgres:5432 ./docker-app-entrypoint.sh
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./occams:/app/occams
      - ./alembic:/app/alembic
      - ./develop.ini:/app/develop.ini
      - ./bower.json:/app/bower.json
      - ./tests:/app/tests
      - blobs:/files/blobs
      - exports:/files/exports

  tasks:
    build:
      context: .
      target: development
    command: dockerize -wait tcp://postgres:5432 ./docker-tasks-entrypoint.sh
    restart: always
    depends_on:
      - postgres
      - redis
    volumes:
      - ./occams:/app/occams
      - ./develop.ini:/app/develop.ini
      - blobs:/files/uploads
      - exports:/files/exports

  postgres:
    build: ./postgres
    restart: always
    environment:
      - POSTGRES_USER=occams
      - POSTGRES_PASSWORD=occams
      - POSTGRES_DB=occams
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data/

  postgres-test:
    build: ./postgres
    restart: always
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    tmpfs: /var/lib/postgresql/data
    ports:
      - "6543:5432"

  redis:
    image: redis:5.0.8
    restart: always
    ports:
      - "6379:6379"

volumes:
  blobs:
  exports:
  postgres:
