#
# Development environment services
# DO NOT USE FOR PRODUCTION
#

app:
  build: .
  command: dockerize -wait tcp://postgres:5432 ./docker-app-entrypoint.sh
  restart: always
  ports:
    - "3000:3000"
  links:
    - postgres:postgres
    - postgres-tests:postgres-tests
    - redis:redis
  volumes:
    - ./occams:/app/occams
    - ./alembic:/app/alembic
    - ./develop.ini:/app/develop.ini
    - ./bower.json:/app/bower.json
    - ./tests:/app/tests
    - uploads:/files/uploads
    - exports:/files/exports

celery:
  build: .
  command: dockerize -wait tcp://postgres:5432 ./docker-celery-entrypoint.sh
  restart: always
  environment:
    - C_FORCE_ROOT=1
  links:
    - postgres:postgres
    - redis:redis
  volumes_from:
    - app

postgres:
  build: https://github.com/razorlabs/pg-json-audit-trigger.git
  restart: always
  environment:
    - POSTGRES_USER=occams
    - POSTGRES_DB=occams
  ports:
    - "5432:5432"
  volumes:
    - postgres:/var/lib/postgresql/data/

postgres-tests:
  build: https://github.com/razorlabs/pg-json-audit-trigger.git
  restart: always
  environment:
    - POSTGRES_USER=test
    - POSTGRES_DB=test
  ports:
    - "6543:5432"

redis:
  image: redis:latest
  restart: always
  ports:
    - "6379:6379"
